{{- range .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .url }}
  username: {{ .username }}
  password: {{ .password }}
  {{- if $.Values.repoConfig }}
  {{- if $.Values.repoConfig.insecure }}
  insecure: {{ $.Values.repoConfig.insecure | quote }}
  {{- end }}
  {{- if $.Values.repoConfig.enableLfs }}
  enableLfs: {{ $.Values.repoConfig.enableLfs | quote }}
  {{- end }}
  {{- end }}
{{- end }}