namespace: default

image:
  repository: 826232761489.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: v1.0.3
  pullPolicy: IfNotPresent
  command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

hpa:
  minReplicas: 2
  maxReplicas: 6
  averageUtilization: 70

replicaCount: 2